- name: Копіювання Dockerfile
copy:
src: "{{ playbook_dir }}/../Dockerfile"
dest: /home/ubuntu/Dockerfile
- name: Копіювання шаблону конфігурації
template:
src: config.cfg.j2
dest: /home/ubuntu/cowrie.cfg
- name: Запуск контейнера honeypot
shell: |
docker build -t honeypot .
docker run -d --name honeypot -p 2222:2222 honeypot
